# Generated by Django 4.1.2 on 2022-10-17 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0002_remove_new_price_alter_new_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='quantity',
        ),
    ]
