# Generated by Django 4.1.2 on 2022-10-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0003_remove_new_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
