# Generated by Django 4.1.2 on 2022-10-19 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0004_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AddField(
            model_name='new',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
