# Generated by Django 4.1.2 on 2022-10-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0005_delete_todo_new_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100000, unique=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='name',
            field=models.CharField(max_length=100000, unique=True),
        ),
    ]
