# Generated by Django 4.1.2 on 2022-10-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0007_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
