# Generated by Django 4.1.2 on 2022-10-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0008_delete_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='category',
            new_name='author',
        ),
    ]
