# Generated by Django 4.1.2 on 2022-10-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0009_rename_category_author_rename_category_new_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='author',
            new_name='category',
        ),
    ]
