# Generated by Django 4.0.6 on 2022-11-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersSubscriptions',
        ),
    ]
